name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Production Build
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.2.0
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
          build_configuration: production
          base_href: /my-spotify-stats/
          deploy_branch: gh-pages
          build_folder: dist/my-spotify-stats
          run_lint: true
